# Generated by Django 4.2.3 on 2023-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='available_evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='available_morning',
            field=models.BooleanField(default=False),
        ),
    ]
