# Generated by Django 4.2.3 on 2023-09-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_trainer_available_evening_trainer_available_morning'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
